name: myapp
worktree_naming: Add feature
todos:
  - description: Implement login feature
    status: done
    worktree: myapp-login
  - description: Add user profile page
    status: pending
    worktree: myapp-profile
windows:
  - name: editor
    command: null
  - name: server
    command: omnara --dangerously-skip-permissions
  - name: shell
    command: null
